### ISSUE TITLE
Passport Parameters

### ISSUE THREAD

**Issue by Gr8z** [Alex-Levacher/Lumie#10]
How should I use passport authenticate function with lumie?

This is my original route:
```js
router.get(
  "/discord/callback",
  passport.authenticate("discord"),
  (req, res) => res.redirect("/")
);
```

The converted function that doesn't work:
```js
const callback = (req, res) => {
  passport.authenticate("discord");
  res.redirect("/");
};

module.exports = {
  "/discord/callback": {
    get: {
      action: callback,
      level: "public"
    }
  }
};
```

**Comment by glimow** [comment]
Hi @Gr8z, I think that's because `passport.authenticate("discord");` is a middleware, so you should specify Lumie to use it as one like that:
```javascript
const callback = (req, res) => {
  res.redirect("/");
};

module.exports = {
  "/discord/callback": {
    get: {
      action: callback,
      level: "public",
      middlewares: [passport.authenticate("discord")]
    }
  }
};
```
If you want to know more about express and its middlewares there are plenty of tutorials out there. For an exhaustive approach I personally liked [Falvio Copes's free *The Express.js Handbook*](https://flaviocopes.com/page/ebooks-links/). :)

**Comment by Gr8z** [comment]
That makes sense. Thank you for the clear explanation.
