### ISSUE TITLE
Root dynamic routes

### ISSUE THREAD

**Issue by Livog** [Alex-Levacher/Lumie#14]
I could not find anything about this in the documentation so I'm guessing this is not thought of yet.

So I have my `/api/`path which is the "root", and then I wanted to listen to a parameter right after like this: `/api/:project`. To create this you could prefix the filename with an underscore.
The naming structure would be `_project-get.js`
Which would generate:
```
public      get      /api/:project
```
Could this be something to implement, or is this already possible? 

EDIT**
I noticed that you could name it `project.routing.js` and it would give you the result I wanted. But I think it creates confusion of where the action is placed since its in a routing named file. Best way to solve this solution?

**Comment by Alex-Levacher** [comment]
Hey @Livog, a solution I see is to create a `project.routig.js` at the root of your Lumie files (controllers folder for instance) and make something like:
```js
const project = (req, res) => {
  res.json({ msg: `I am the project ${req.params.project}`});
};

module.exports = {
  '/:project(apple|banana)': {
    get: {
      action: project,
      level: 'public'
    }
  }
};
```
Don't forget to have a regex in your routing configuration in order to not override other endpoints. I gave you an example that takes banana or apple as existing projects.

If you don't want to create the action in the routing file, you can create a folder `projects` and define the actions inside, but you'll have to keep the `project.routing.js` at the root.

A completely different solution would be to create: `/api/project/:name`. You can follow this [example](https://github.com/Alex-Levacher/Lumie/tree/master/example/controllers/cars) if you choose this solution

**Comment by Alex-Levacher** [comment]
@Livog Is my answer was helpful?
